<?php

/**
 * @file
 * Theme file for players_theme.
 */

use \Drupal\paragraphs\Entity\Paragraph;
use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_HOOK().
 */
function pinc_theme_preprocess_page(&$variables) {

  // Get the theme path and set a variable.
  $themeHandler = \Drupal::service('theme_handler');
  $variables['theme_path'] = $themeHandler->getTheme($themeHandler->getDefault())->getPath();

  // Add variable for logged in users.
  if (\Drupal::currentUser()->isAuthenticated()) {
    $variables['logged_in'] = TRUE;
  }
  else {
    $variables['logged_in'] = FALSE;
  }
}
